name: xinsight
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - altair==5.4.1
      - asttokens==2.4.1
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - cachetools==5.5.0
      - certifi==2024.8.30
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmdstanpy==1.2.4
      - colour==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.1.1
      - dtreeviz==2.2.2
      - duckdb==1.0.0
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - faker==28.4.1
      - favicon==0.7.0
      - fonttools==4.53.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - holidays==0.56
      - htbuilder==0.6.2
      - idna==3.8
      - importlib-resources==6.4.4
      - iniconfig==2.0.0
      - ipython==8.27.0
      - isodate==0.6.1
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpickle==3.3.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - lightgbm==4.5.0
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markdownlit==0.0.7
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - more-itertools==10.4.0
      - narwhals==1.6.2
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-nccl-cu12==2.22.3
      - openpyxl==3.1.3
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - plotly==5.24.0
      - pluggy==1.5.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - prophet==1.1.5
      - protobuf==5.28.0
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pydeck==0.9.1
      - pygments==2.18.0
      - pymdown-extensions==10.9
      - pyparsing==3.1.4
      - pytest==8.3.2
      - python-dateutil==2.9.0.post0
      - graphviz==0.20.3
      - pytz==2024.1
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - rdflib==7.0.0
      - referencing==0.35.1
      - reportlab==4.2.2
      - requests==2.32.3
      - rich==13.8.0
      - rpds-py==0.20.0
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - six==1.16.0
      - smmap==5.0.1
      - soupsieve==2.6
      - st-annotated-text==4.0.1
      - st-theme==1.2.3
      - stack-data==0.6.3
      - stanio==0.5.1
      - streamlit==1.38.0
      - streamlit-ace==0.1.1
      - streamlit-camera-input-live==0.2.0
      - streamlit-card==1.0.2
      - streamlit-embedcode==0.1.2
      - streamlit-extras==0.4.7
      - streamlit-faker==0.0.3
      - streamlit-image-coordinates==0.1.9
      - streamlit-keyup==0.2.4
      - streamlit-option-menu==0.3.13
      - streamlit-toggle-switch==1.0.2
      - streamlit-vertical-slider==2.5.5
      - tenacity==8.5.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - tomli==2.0.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - validators==0.34.0
      - vega-datasets==0.9.0
      - vegafusion==1.6.9
      - vegafusion-python-embed==1.6.9
      - vl-convert-python==1.6.1
      - watchdog==4.0.2
      - wcwidth==0.2.13
      - xgboost==2.1.1
prefix: /home/tih_isi_1/miniconda3/envs/xinsight
